apiVersion: v1
kind: Secret
metadata:
  name: teststoragesecret
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: Minio Data Connection
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  # The following keys are needed while https://github.com/kubeflow/pipelines/issues/9689 is open
  accesskey: ""
  secretkey: ""
type: Opaque
