apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../argo
- ../../base
namespace: opendatahub
vars:
  - name: IMAGES_ARGO_SERVER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_ARGO_SERVER
