---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: dspipelines.dspipelines.opendatahub.io
spec:
  group: dspipelines.opendatahub.io
  names:
    kind: DSPipeline
    listKind: DSPipelineList
    plural: dspipelines
    singular: dspipeline
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              apiServer:
                default:
                  deploy: true
                description: APIService specifies the Kubeflow Apiserver configurations
                properties:
                  applyTektonCustomResource:
                    default: true
                    type: boolean
                  archiveLogs:
                    default: false
                    type: boolean
                  artifactImage:
                    type: string
                  artifactScriptConfigMap:
                    properties:
                      key:
                        type: string
                      name:
                        type: string
                    type: object
                  autoUpdatePipelineDefaultVersion:
                    default: true
                    type: boolean
                  cacheImage:
                    type: string
                  collectMetrics:
                    default: true
                    type: boolean
                  dbConfigConMaxLifetimeSec:
                    default: 120
                    type: integer
                  deploy:
                    default: true
                    type: boolean
                  image:
                    type: string
                  injectDefaultScript:
                    default: true
                    type: boolean
                  moveResultsImage:
                    type: string
                  resources:
                    description: ResourceRequirements structures compute resource
                      requirements. Replaces ResourceRequirements from corev1 which
                      also includes optional storage field. We handle storage field
                      separately, and should not include it as a subfield for Resources.
                    properties:
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                  stripEOF:
                    default: true
                    type: boolean
                  terminateStatus:
                    default: Cancelled
                    type: string
                  trackArtifacts:
                    default: true
                    type: boolean
                type: object
              database:
                default:
                  mariaDB:
                    deploy: true
                properties:
                  externalDB:
                    properties:
                      host:
                        type: string
                      passwordSecret:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        type: object
                      pipelineDBName:
                        type: string
                      port:
                        type: string
                      username:
                        type: string
                    type: object
                  mariaDB:
                    properties:
                      deploy:
                        default: true
                        type: boolean
                      image:
                        type: string
                      passwordSecret:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        type: object
                      pipelineDBName:
                        default: mlpipeline
                        type: string
                      pvcSize:
                        default: 10Gi
                        type: string
                      resources:
                        description: ResourceRequirements structures compute resource
                          requirements. Replaces ResourceRequirements from corev1
                          which also includes optional storage field. We handle storage
                          field separately, and should not include it as a subfield
                          for Resources.
                        properties:
                          limits:
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                            type: object
                          requests:
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                            type: object
                        type: object
                      username:
                        default: mlpipeline
                        type: string
                    type: object
                type: object
              mlpipelineUI:
                default:
                  deploy: true
                properties:
                  configMap:
                    type: string
                  deploy:
                    default: true
                    type: boolean
                  image:
                    type: string
                  resources:
                    description: ResourceRequirements structures compute resource
                      requirements. Replaces ResourceRequirements from corev1 which
                      also includes optional storage field. We handle storage field
                      separately, and should not include it as a subfield for Resources.
                    properties:
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                type: object
              objectStorage:
                default:
                  minio:
                    deploy: true
                properties:
                  externalStorage:
                    properties:
                      bucket:
                        type: string
                      host:
                        type: string
                      port:
                        type: string
                      s3CredentialsSecret:
                        properties:
                          accessKey:
                            description: The "Keys" in the k8sSecret key/value pairs.
                              Not to be confused with the values.
                            type: string
                          secretKey:
                            type: string
                          secretName:
                            type: string
                        type: object
                      scheme:
                        type: string
                    type: object
                  minio:
                    properties:
                      bucket:
                        default: mlpipeline
                        type: string
                      deploy:
                        default: true
                        type: boolean
                      image:
                        type: string
                      pvcSize:
                        default: 10Gi
                        type: string
                      resources:
                        description: ResourceRequirements structures compute resource
                          requirements. Replaces ResourceRequirements from corev1
                          which also includes optional storage field. We handle storage
                          field separately, and should not include it as a subfield
                          for Resources.
                        properties:
                          limits:
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                            type: object
                          requests:
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                            type: object
                        type: object
                      s3CredentialsSecret:
                        properties:
                          accessKey:
                            description: The "Keys" in the k8sSecret key/value pairs.
                              Not to be confused with the values.
                            type: string
                          secretKey:
                            type: string
                          secretName:
                            type: string
                        type: object
                    type: object
                type: object
              persistenceAgent:
                default:
                  deploy: true
                properties:
                  deploy:
                    default: true
                    type: boolean
                  image:
                    type: string
                  numWorkers:
                    default: 2
                    type: integer
                  resources:
                    description: ResourceRequirements structures compute resource
                      requirements. Replaces ResourceRequirements from corev1 which
                      also includes optional storage field. We handle storage field
                      separately, and should not include it as a subfield for Resources.
                    properties:
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                type: object
              scheduledWorkflow:
                default:
                  deploy: true
                properties:
                  cronScheduleTimezone:
                    default: UTC
                    type: string
                  deploy:
                    default: true
                    type: boolean
                  image:
                    type: string
                  resources:
                    description: ResourceRequirements structures compute resource
                      requirements. Replaces ResourceRequirements from corev1 which
                      also includes optional storage field. We handle storage field
                      separately, and should not include it as a subfield for Resources.
                    properties:
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                type: object
              viewerCRD:
                default:
                  deploy: false
                properties:
                  deploy:
                    default: false
                    type: boolean
                  image:
                    type: string
                  maxNumViewer:
                    default: 50
                    type: integer
                  resources:
                    description: ResourceRequirements structures compute resource
                      requirements. Replaces ResourceRequirements from corev1 which
                      also includes optional storage field. We handle storage field
                      separately, and should not include it as a subfield for Resources.
                    properties:
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                type: object
            type: object
          status:
            properties:
              conditions:
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource. --- This struct is intended for direct
                    use as an array at the field path .status.conditions.  For example,
                    \n type FooStatus struct{ // Represents the observations of a
                    foo's current state. // Known .status.conditions.type are: \"Available\",
                    \"Progressing\", and \"Degraded\" // +patchMergeKey=type // +patchStrategy=merge
                    // +listType=map // +listMapKey=type Conditions []metav1.Condition
                    `json:\"conditions,omitempty\" patchStrategy:\"merge\" patchMergeKey:\"type\"
                    protobuf:\"bytes,1,rep,name=conditions\"` \n // other fields }"
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition
                        transitioned from one status to another. This should be when
                        the underlying condition changed.  If that is not known, then
                        using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.conditions[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating
                        the reason for the condition's last transition. Producers
                        of specific condition types may define expected values and
                        meanings for this field, and whether the values are considered
                        a guaranteed API. The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        --- Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
